// Generated by Ignite ignite.com/cli

import { StdFee } from "@cosmjs/launchpad";
import { SigningStargateClient, DeliverTxResponse } from "@cosmjs/stargate";
import { EncodeObject, GeneratedType, OfflineSigner, Registry } from "@cosmjs/proto-signing";
import { msgTypes } from './registry';
import { IgniteClient } from "../client"
import { MissingWalletError } from "../helpers"
import { Api } from "./rest";
import { MsgCreateMembershipTokenStatus } from "./types/mitoblockchaindev/tx";
import { MsgCreateDiscountToken } from "./types/mitoblockchaindev/tx";
import { MsgCreateMembershipToken } from "./types/mitoblockchaindev/tx";
import { MsgDeleteMembershipTokenStatus } from "./types/mitoblockchaindev/tx";
import { MsgDeleteDiscountTokenStatus } from "./types/mitoblockchaindev/tx";
import { MsgCreateDiscountTokenStatus } from "./types/mitoblockchaindev/tx";


export { MsgCreateMembershipTokenStatus, MsgCreateDiscountToken, MsgCreateMembershipToken, MsgDeleteMembershipTokenStatus, MsgDeleteDiscountTokenStatus, MsgCreateDiscountTokenStatus };

type sendMsgCreateMembershipTokenStatusParams = {
  value: MsgCreateMembershipTokenStatus,
  fee?: StdFee,
  memo?: string
};

type sendMsgCreateDiscountTokenParams = {
  value: MsgCreateDiscountToken,
  fee?: StdFee,
  memo?: string
};

type sendMsgCreateMembershipTokenParams = {
  value: MsgCreateMembershipToken,
  fee?: StdFee,
  memo?: string
};

type sendMsgDeleteMembershipTokenStatusParams = {
  value: MsgDeleteMembershipTokenStatus,
  fee?: StdFee,
  memo?: string
};

type sendMsgDeleteDiscountTokenStatusParams = {
  value: MsgDeleteDiscountTokenStatus,
  fee?: StdFee,
  memo?: string
};

type sendMsgCreateDiscountTokenStatusParams = {
  value: MsgCreateDiscountTokenStatus,
  fee?: StdFee,
  memo?: string
};


type msgCreateMembershipTokenStatusParams = {
  value: MsgCreateMembershipTokenStatus,
};

type msgCreateDiscountTokenParams = {
  value: MsgCreateDiscountToken,
};

type msgCreateMembershipTokenParams = {
  value: MsgCreateMembershipToken,
};

type msgDeleteMembershipTokenStatusParams = {
  value: MsgDeleteMembershipTokenStatus,
};

type msgDeleteDiscountTokenStatusParams = {
  value: MsgDeleteDiscountTokenStatus,
};

type msgCreateDiscountTokenStatusParams = {
  value: MsgCreateDiscountTokenStatus,
};


export const registry = new Registry(msgTypes);

const defaultFee = {
  amount: [],
  gas: "200000",
};

interface TxClientOptions {
  addr: string
	prefix: string
	signer?: OfflineSigner
}

export const txClient = ({ signer, prefix, addr }: TxClientOptions = { addr: "http://localhost:26657", prefix: "cosmos" }) => {

  return {
		
		async sendMsgCreateMembershipTokenStatus({ value, fee, memo }: sendMsgCreateMembershipTokenStatusParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgCreateMembershipTokenStatus: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgCreateMembershipTokenStatus({ value: MsgCreateMembershipTokenStatus.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgCreateMembershipTokenStatus: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgCreateDiscountToken({ value, fee, memo }: sendMsgCreateDiscountTokenParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgCreateDiscountToken: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgCreateDiscountToken({ value: MsgCreateDiscountToken.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgCreateDiscountToken: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgCreateMembershipToken({ value, fee, memo }: sendMsgCreateMembershipTokenParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgCreateMembershipToken: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgCreateMembershipToken({ value: MsgCreateMembershipToken.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgCreateMembershipToken: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgDeleteMembershipTokenStatus({ value, fee, memo }: sendMsgDeleteMembershipTokenStatusParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgDeleteMembershipTokenStatus: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgDeleteMembershipTokenStatus({ value: MsgDeleteMembershipTokenStatus.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgDeleteMembershipTokenStatus: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgDeleteDiscountTokenStatus({ value, fee, memo }: sendMsgDeleteDiscountTokenStatusParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgDeleteDiscountTokenStatus: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgDeleteDiscountTokenStatus({ value: MsgDeleteDiscountTokenStatus.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgDeleteDiscountTokenStatus: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgCreateDiscountTokenStatus({ value, fee, memo }: sendMsgCreateDiscountTokenStatusParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgCreateDiscountTokenStatus: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgCreateDiscountTokenStatus({ value: MsgCreateDiscountTokenStatus.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgCreateDiscountTokenStatus: Could not broadcast Tx: '+ e.message)
			}
		},
		
		
		msgCreateMembershipTokenStatus({ value }: msgCreateMembershipTokenStatusParams): EncodeObject {
			try {
				return { typeUrl: "/mitoblockchaindev.mitoblockchaindev.MsgCreateMembershipTokenStatus", value: MsgCreateMembershipTokenStatus.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgCreateMembershipTokenStatus: Could not create message: ' + e.message)
			}
		},
		
		msgCreateDiscountToken({ value }: msgCreateDiscountTokenParams): EncodeObject {
			try {
				return { typeUrl: "/mitoblockchaindev.mitoblockchaindev.MsgCreateDiscountToken", value: MsgCreateDiscountToken.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgCreateDiscountToken: Could not create message: ' + e.message)
			}
		},
		
		msgCreateMembershipToken({ value }: msgCreateMembershipTokenParams): EncodeObject {
			try {
				return { typeUrl: "/mitoblockchaindev.mitoblockchaindev.MsgCreateMembershipToken", value: MsgCreateMembershipToken.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgCreateMembershipToken: Could not create message: ' + e.message)
			}
		},
		
		msgDeleteMembershipTokenStatus({ value }: msgDeleteMembershipTokenStatusParams): EncodeObject {
			try {
				return { typeUrl: "/mitoblockchaindev.mitoblockchaindev.MsgDeleteMembershipTokenStatus", value: MsgDeleteMembershipTokenStatus.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgDeleteMembershipTokenStatus: Could not create message: ' + e.message)
			}
		},
		
		msgDeleteDiscountTokenStatus({ value }: msgDeleteDiscountTokenStatusParams): EncodeObject {
			try {
				return { typeUrl: "/mitoblockchaindev.mitoblockchaindev.MsgDeleteDiscountTokenStatus", value: MsgDeleteDiscountTokenStatus.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgDeleteDiscountTokenStatus: Could not create message: ' + e.message)
			}
		},
		
		msgCreateDiscountTokenStatus({ value }: msgCreateDiscountTokenStatusParams): EncodeObject {
			try {
				return { typeUrl: "/mitoblockchaindev.mitoblockchaindev.MsgCreateDiscountTokenStatus", value: MsgCreateDiscountTokenStatus.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgCreateDiscountTokenStatus: Could not create message: ' + e.message)
			}
		},
		
	}
};

interface QueryClientOptions {
  addr: string
}

export const queryClient = ({ addr: addr }: QueryClientOptions = { addr: "http://localhost:1317" }) => {
  return new Api({ baseUrl: addr });
};

class SDKModule {
	public query: ReturnType<typeof queryClient>;
	public tx: ReturnType<typeof txClient>;
	
	public registry: Array<[string, GeneratedType]>;

	constructor(client: IgniteClient) {		
	
		this.query = queryClient({ addr: client.env.apiURL });
		this.tx = txClient({ signer: client.signer, addr: client.env.rpcURL, prefix: client.env.prefix ?? "cosmos" });
	}
};

const Module = (test: IgniteClient) => {
	return {
		module: {
			MitoblockchaindevMitoblockchaindev: new SDKModule(test)
		},
		registry: msgTypes
  }
}
export default Module;