// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mitoblockchain/discount_token.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type DiscountToken struct {
	Creator           string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Id                uint64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp         string `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ActivityName      string `protobuf:"bytes,4,opt,name=activityName,proto3" json:"activityName,omitempty"`
	Score             string `protobuf:"bytes,5,opt,name=score,proto3" json:"score,omitempty"`
	Message           string `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	DiscountValue     string `protobuf:"bytes,7,opt,name=discountValue,proto3" json:"discountValue,omitempty"`
	EligibleCompanies string `protobuf:"bytes,8,opt,name=eligibleCompanies,proto3" json:"eligibleCompanies,omitempty"`
	ItemType          string `protobuf:"bytes,9,opt,name=itemType,proto3" json:"itemType,omitempty"`
	ExpiryDate        string `protobuf:"bytes,10,opt,name=expiryDate,proto3" json:"expiryDate,omitempty"`
}

func (m *DiscountToken) Reset()         { *m = DiscountToken{} }
func (m *DiscountToken) String() string { return proto.CompactTextString(m) }
func (*DiscountToken) ProtoMessage()    {}
func (*DiscountToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e8f5b2845840978, []int{0}
}
func (m *DiscountToken) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DiscountToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DiscountToken.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DiscountToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiscountToken.Merge(m, src)
}
func (m *DiscountToken) XXX_Size() int {
	return m.Size()
}
func (m *DiscountToken) XXX_DiscardUnknown() {
	xxx_messageInfo_DiscountToken.DiscardUnknown(m)
}

var xxx_messageInfo_DiscountToken proto.InternalMessageInfo

func (m *DiscountToken) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *DiscountToken) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DiscountToken) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *DiscountToken) GetActivityName() string {
	if m != nil {
		return m.ActivityName
	}
	return ""
}

func (m *DiscountToken) GetScore() string {
	if m != nil {
		return m.Score
	}
	return ""
}

func (m *DiscountToken) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *DiscountToken) GetDiscountValue() string {
	if m != nil {
		return m.DiscountValue
	}
	return ""
}

func (m *DiscountToken) GetEligibleCompanies() string {
	if m != nil {
		return m.EligibleCompanies
	}
	return ""
}

func (m *DiscountToken) GetItemType() string {
	if m != nil {
		return m.ItemType
	}
	return ""
}

func (m *DiscountToken) GetExpiryDate() string {
	if m != nil {
		return m.ExpiryDate
	}
	return ""
}

func init() {
	proto.RegisterType((*DiscountToken)(nil), "mitoblock.mitoblockchain.mitoblockchain.DiscountToken")
}

func init() {
	proto.RegisterFile("mitoblockchain/discount_token.proto", fileDescriptor_7e8f5b2845840978)
}

var fileDescriptor_7e8f5b2845840978 = []byte{
	// 315 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0xbd, 0x4e, 0x32, 0x41,
	0x14, 0x86, 0xd9, 0xfd, 0xf8, 0x3d, 0xf9, 0x30, 0x71, 0x62, 0x31, 0x31, 0x66, 0x43, 0xd0, 0x44,
	0x0a, 0x03, 0x85, 0x9d, 0xa5, 0x52, 0x5b, 0x10, 0x62, 0x61, 0x63, 0x66, 0x87, 0x13, 0x38, 0x61,
	0x67, 0x67, 0xb3, 0x73, 0x30, 0xec, 0x5d, 0x78, 0x3f, 0xde, 0x80, 0x25, 0xa5, 0xa5, 0x81, 0x1b,
	0x31, 0x0c, 0x3f, 0x0a, 0x96, 0xef, 0xf3, 0x3e, 0x39, 0x39, 0x33, 0x07, 0x2e, 0x0d, 0xb1, 0x8d,
	0x13, 0xab, 0xa7, 0x7a, 0xa2, 0x28, 0xed, 0x8d, 0xc8, 0x69, 0x3b, 0x4b, 0xf9, 0x85, 0xed, 0x14,
	0xd3, 0x6e, 0x96, 0x5b, 0xb6, 0xe2, 0x7a, 0x2f, 0x75, 0x0f, 0xf5, 0xa3, 0xd8, 0x7e, 0x0f, 0xa1,
	0xd9, 0xdf, 0x4e, 0x18, 0xae, 0x07, 0x08, 0x09, 0x35, 0x9d, 0xa3, 0x62, 0x9b, 0xcb, 0xa0, 0x15,
	0x74, 0x1a, 0x83, 0x5d, 0x14, 0x27, 0x10, 0xd2, 0x48, 0x86, 0xad, 0xa0, 0x53, 0x1e, 0x84, 0x34,
	0x12, 0x17, 0xd0, 0x60, 0x32, 0xe8, 0x58, 0x99, 0x4c, 0xfe, 0xf3, 0xee, 0x0f, 0x10, 0x6d, 0xf8,
	0xaf, 0x34, 0xd3, 0x2b, 0x71, 0xf1, 0xa8, 0x0c, 0xca, 0xb2, 0x17, 0x0e, 0x98, 0x38, 0x83, 0x8a,
	0xd3, 0x36, 0x47, 0x59, 0xf1, 0xe5, 0x26, 0xac, 0x37, 0x30, 0xe8, 0x9c, 0x1a, 0xa3, 0xac, 0x6e,
	0x36, 0xd8, 0x46, 0x71, 0x05, 0xcd, 0xdd, 0x73, 0x9f, 0x54, 0x32, 0x43, 0x59, 0xf3, 0xfd, 0x21,
	0x14, 0x37, 0x70, 0x8a, 0x09, 0x8d, 0x29, 0x4e, 0xf0, 0xc1, 0x9a, 0x4c, 0xa5, 0x84, 0x4e, 0xd6,
	0xbd, 0xf9, 0xb7, 0x10, 0xe7, 0x50, 0x27, 0x46, 0x33, 0x2c, 0x32, 0x94, 0x0d, 0x2f, 0xed, 0xb3,
	0x88, 0x00, 0x70, 0x9e, 0x51, 0x5e, 0xf4, 0x15, 0xa3, 0x04, 0xdf, 0xfe, 0x22, 0xf7, 0xc3, 0x8f,
	0x65, 0x14, 0x2c, 0x96, 0x51, 0xf0, 0xb5, 0x8c, 0x82, 0xb7, 0x55, 0x54, 0x5a, 0xac, 0xa2, 0xd2,
	0xe7, 0x2a, 0x2a, 0x3d, 0xdf, 0x8d, 0x89, 0x27, 0xb3, 0xb8, 0xab, 0xad, 0xe9, 0xed, 0xbf, 0xbc,
	0x77, 0x74, 0xba, 0xf9, 0x31, 0xe0, 0x22, 0x43, 0x17, 0x57, 0xfd, 0x0d, 0x6f, 0xbf, 0x03, 0x00,
	0x00, 0xff, 0xff, 0x47, 0xc2, 0x62, 0x81, 0xea, 0x01, 0x00, 0x00,
}

func (m *DiscountToken) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DiscountToken) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DiscountToken) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ExpiryDate) > 0 {
		i -= len(m.ExpiryDate)
		copy(dAtA[i:], m.ExpiryDate)
		i = encodeVarintDiscountToken(dAtA, i, uint64(len(m.ExpiryDate)))
		i--
		dAtA[i] = 0x52
	}
	if len(m.ItemType) > 0 {
		i -= len(m.ItemType)
		copy(dAtA[i:], m.ItemType)
		i = encodeVarintDiscountToken(dAtA, i, uint64(len(m.ItemType)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.EligibleCompanies) > 0 {
		i -= len(m.EligibleCompanies)
		copy(dAtA[i:], m.EligibleCompanies)
		i = encodeVarintDiscountToken(dAtA, i, uint64(len(m.EligibleCompanies)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.DiscountValue) > 0 {
		i -= len(m.DiscountValue)
		copy(dAtA[i:], m.DiscountValue)
		i = encodeVarintDiscountToken(dAtA, i, uint64(len(m.DiscountValue)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Message) > 0 {
		i -= len(m.Message)
		copy(dAtA[i:], m.Message)
		i = encodeVarintDiscountToken(dAtA, i, uint64(len(m.Message)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Score) > 0 {
		i -= len(m.Score)
		copy(dAtA[i:], m.Score)
		i = encodeVarintDiscountToken(dAtA, i, uint64(len(m.Score)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.ActivityName) > 0 {
		i -= len(m.ActivityName)
		copy(dAtA[i:], m.ActivityName)
		i = encodeVarintDiscountToken(dAtA, i, uint64(len(m.ActivityName)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Timestamp) > 0 {
		i -= len(m.Timestamp)
		copy(dAtA[i:], m.Timestamp)
		i = encodeVarintDiscountToken(dAtA, i, uint64(len(m.Timestamp)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Id != 0 {
		i = encodeVarintDiscountToken(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintDiscountToken(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintDiscountToken(dAtA []byte, offset int, v uint64) int {
	offset -= sovDiscountToken(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *DiscountToken) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovDiscountToken(uint64(l))
	}
	if m.Id != 0 {
		n += 1 + sovDiscountToken(uint64(m.Id))
	}
	l = len(m.Timestamp)
	if l > 0 {
		n += 1 + l + sovDiscountToken(uint64(l))
	}
	l = len(m.ActivityName)
	if l > 0 {
		n += 1 + l + sovDiscountToken(uint64(l))
	}
	l = len(m.Score)
	if l > 0 {
		n += 1 + l + sovDiscountToken(uint64(l))
	}
	l = len(m.Message)
	if l > 0 {
		n += 1 + l + sovDiscountToken(uint64(l))
	}
	l = len(m.DiscountValue)
	if l > 0 {
		n += 1 + l + sovDiscountToken(uint64(l))
	}
	l = len(m.EligibleCompanies)
	if l > 0 {
		n += 1 + l + sovDiscountToken(uint64(l))
	}
	l = len(m.ItemType)
	if l > 0 {
		n += 1 + l + sovDiscountToken(uint64(l))
	}
	l = len(m.ExpiryDate)
	if l > 0 {
		n += 1 + l + sovDiscountToken(uint64(l))
	}
	return n
}

func sovDiscountToken(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozDiscountToken(x uint64) (n int) {
	return sovDiscountToken(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *DiscountToken) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDiscountToken
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DiscountToken: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DiscountToken: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDiscountToken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDiscountToken
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDiscountToken
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDiscountToken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDiscountToken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDiscountToken
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDiscountToken
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Timestamp = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActivityName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDiscountToken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDiscountToken
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDiscountToken
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ActivityName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Score", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDiscountToken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDiscountToken
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDiscountToken
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Score = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Message", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDiscountToken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDiscountToken
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDiscountToken
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Message = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DiscountValue", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDiscountToken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDiscountToken
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDiscountToken
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DiscountValue = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EligibleCompanies", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDiscountToken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDiscountToken
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDiscountToken
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EligibleCompanies = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ItemType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDiscountToken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDiscountToken
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDiscountToken
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ItemType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpiryDate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDiscountToken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDiscountToken
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDiscountToken
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ExpiryDate = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDiscountToken(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDiscountToken
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipDiscountToken(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowDiscountToken
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDiscountToken
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDiscountToken
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthDiscountToken
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupDiscountToken
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthDiscountToken
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthDiscountToken        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowDiscountToken          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupDiscountToken = fmt.Errorf("proto: unexpected end of group")
)
